### ISSUE TITLE
Create login pages for students, teachers, admin

### ISSUE THREAD

**Issue by Akki019** [KhushiJain2004/Attendance-management-system-Devops-lab-#4]

**Comment by Kashishturan** [comment]
Rajat this task was assigned to Khushi during first team meet. So you have been unassigned from this task. Please attend team meets to know your tasks and workflow of our project.

**Comment by KhushiJain2004** [comment]
i am making the connector page for the seperate login pages ..

**Comment by Aaryanb45** [comment]
yh I will make the navbar
